name: Push-Changes-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}

      - name: Executing remote ssh commands using ssh key
        run: |
          pwd
          ls -a
          cd ..
          pwd
          ls -a
          # sudo apt install python3-venv -y
          # sudo python3 -m venv LCvenv
          # source LCvenv/bin/activate
          # sudo pip install -r requirements.txt
          # sudo bash -c 'echo "OPENAI_API_KEY=${OPENAI_API_KEY}" > .env'
          # python3 -m uvicorn main:app --host 0.0.0.0 --port 8003
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
